Sign up and basic rails update
vibalcam/match-my-fashion-public-CodeCreators pull request #5
Opened 2023-02-20 20:58 UTC by AJ1904

2023-02-23 04:27 UTC, vibalcam commented
Has already been merged with the seeding

Needs test cases for login (sign in and sign up)

2023-02-23 04:28 UTC, vibalcam requested changes
Needs test cases for login (sign in and sign up)

These changes have been merged by Lance's seeding. Work from new master.

2023-02-24 23:30 UTC, AJ1904 commented
> Needs test cases for login (sign in and sign up)
> 
> These changes have been merged by Lance's seeding. Work from new master.

Test case - user_story_2.feature

2023-02-25 04:54 UTC, vibalcam approved these changes

2023-02-25 04:56 UTC, merged