search result UI modification
vibalcam/match-my-fashion-public-CodeCreators pull request #9
Opened 2023-03-02 17:29 UTC by wenyuanli0326

1\ change the color of the search box
2\ show informations about the professionals without having to hovering on the photos

2023-03-03 18:37 UTC, vibalcam requested changes
Looks good but needs test.

Create a cucumber test for the hovering feature.

2023-03-09 20:57 UTC, AJ1904 commented
Added rpsec test for search view.
Before -
<img width="908" alt="Pasted Graphic" src="https://user-images.githubusercontent.com/49027490/224155836-af4b01d8-ac89-4d87-853f-1840b4258923.png">
After -
<img width="908" alt="Pasted Graphic 1" src="https://user-images.githubusercontent.com/49027490/224155874-5244840a-4efb-43ac-a6fc-89f2a5b9a27c.png">

Run test by : rspec spec/views/search_profile/search.html.erb_spec.rb

2023-03-10 15:37 UTC, vibalcam approved these changes

2023-03-10 15:38 UTC, vibalcam commented
No cucumber test still. The rspec does not test the hovering feature used.

Accept it but it needs to be added later

2023-03-10 15:38 UTC, merged